name: Run soushuba qiandao
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SOUSHUBA_HOSTNAME: ${{ secrets.SOUSHUBA_HOSTNAME }}
      SOUSHUBA_USERNAME: ${{ secrets.SOUSHUBA_USERNAME }}
      SOUSHUBA_PASSWORD: ${{ secrets.SOUSHUBA_PASSWORD }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install --upgrade certifi
      # 获取目标网站的PEM格式证书
      - run: openssl s_client -connect g9dr.bnm.9vdrg4er5.com:443 -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM > certificate.pem
      - run: python -c "import certifi; print(certifi.where())"
      - run: cat certificate.pem >> $(python -c "import certifi; print(certifi.where())")
      - run: pip install -r requirements.txt
      - run: python soushuba.py
